version: '3'

services:
  #nest-app:
    #container_name: nest-app
    #build: ./
    #ports:
    #  - 3000:3000
    #depends_on:
    #  - db
    #env_file:
    #  - .env
    #volumes:
    #  - .:/usr/src/app
    #  - /usr/src/app/node_modules
  db:
    image: mysql:8.0.30-debian
    environment:
      - MYSQL_ROOT_PASSWORD=root 
      - MYSQL_DATABASE=shortly
    ports:
      - 3306:3306 
    volumes:
      - ./.docker/dbdata:/var/lib/mysql 
      